### ISSUE TITLE
tasks fail when artifact directories not found

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-worker#277] opened 2017-05-11 15:29 UTC
https://public-artifacts.taskcluster.net/YPn15FnCTlWApzu7fgDI_A/0/public/logs/live_backing.log
```
+ exit 0
[taskcluster:error]  No folder was found at 'build/blobber_upload_dir', artifact upload failed.
[taskcluster:error]  No folder was found at 'build/upload/logs', artifact upload failed.
```
and the task is marked failed.

I can see the reasoning behind this, but it doesn't match [docker-worker's behavior](https://github.com/taskcluster/docker-worker/blob/master/src/lib/features/artifacts.js#L101).

At least for directories, I see this as a feature.  For example, a task might only dump output to `crashinfo/` if there's a crash -- if there was no crash, and the execution was successful, then the task should not be marked failed.  This is problematic for https://bugzilla.mozilla.org/show_bug.cgi?id=1357753 in particular, where talos jobs do not necessarily populate the blob upload dir, but could if a dev wanted to produce extra output for debugging.

**Comment by djmitche** [comment] 2017-05-12 19:27
I'm going to work around this in-tree (it just means adding some `mkdir` calls), but I'd be interested in some feedback from other users as to whether this is a good idea.

**Comment by jonasfj** [comment] 2017-06-14 18:41
I think this was a major design flaw in docker-worker, that happened by accident.

If a artifact file or folder is declared and missing, the task should be resolved as failed.

You should create the artifact folders in your Dockerfile, virtual machine image, or if using native-engine you should manually delete/create them to ensure they are deleted between tasks...

**Comment by jonasfj** [comment] 2018-02-23 20:06
Closing this as things works as intended... I don't want persist the docker-worker behavior.

**Closed by jonasfj** 2018-02-23 20:06 UTC
Labels: invalid
